/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import java.text.DecimalFormat;

/**
 *
 * @author HARSH
 */
public class Calculate extends javax.swing.JFrame {
    String str="",str1="",str2="",ans="";
    int nflag=0,pflag=0,op=0;
    /**
     * Creates new form Calculate
     */
    public Calculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
             
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num10 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JComboBox<>();
        op1 = new javax.swing.JButton();
        op2 = new javax.swing.JButton();
        op3 = new javax.swing.JButton();
        op4 = new javax.swing.JButton();
        op5 = new javax.swing.JButton();
        op6 = new javax.swing.JButton();
        op7 = new javax.swing.JButton();
        op8 = new javax.swing.JButton();
        op9 = new javax.swing.JButton();
        op10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(200, 200));

        num1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        num10.setText("0");
        num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num10ActionPerformed(evt);
            }
        });

        t1.setFocusable(false);

        t2.setFocusable(false);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        op1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op1.setText("+");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        op2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op2.setText("-");
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });

        op3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op3.setText("*");
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });

        op4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op4.setText("/");
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4ActionPerformed(evt);
            }
        });

        op5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op5.setText("=");
        op5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op5ActionPerformed(evt);
            }
        });

        op6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op6.setText("X");
        op6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op6ActionPerformed(evt);
            }
        });

        op7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op7.setText("(");
        op7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op7ActionPerformed(evt);
            }
        });

        op8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op8.setText(")");
        op8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op8ActionPerformed(evt);
            }
        });

        op9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op9.setText("C");
        op9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op9ActionPerformed(evt);
            }
        });

        op10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        op10.setText(".");
        op10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op10ActionPerformed(evt);
            }
        });

        jLabel1.setText("History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(t1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(op6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(op7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(op8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(op5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(op9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(op4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(op10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t3)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        str += "1";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "1";
        } else {
            str2 += "1";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }

        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        str += "2";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "2";
        } else {
            str2 += "2";
        }
        if (str2.equals("")) {
            str2 = "0";
        }

        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }

        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        str += "3";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "3";
        } else {
            str2 += "3";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }

        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        str += "4";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "4";
        } else {
            str2 += "4";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }

        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        str += "5";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "5";
        } else {
            str2 += "5";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }

        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        str += "6";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "6";
        } else {
            str2 += "6";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }

        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        str += "7";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "7";
        } else {
            str2 += "7";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }

        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        str += "8";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "8";
        } else {
            str2 += "8";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }
        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        str += "9";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "9";
        } else {
            str2 += "9";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }
        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num9ActionPerformed

    private void num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num10ActionPerformed
        // TODO add your handling code here:
        str += "0";
        t1.setText(str);
        if (nflag == pflag) {
            str1 += "0";
        } else {
            str2 += "0";
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }
        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
    }//GEN-LAST:event_num10ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:     
        String temp=t3.getSelectedItem().toString();
        t1.setText(temp.substring(0,temp.lastIndexOf("=")));
        t2.setText(temp.substring(temp.lastIndexOf("=")+1));
        
    }//GEN-LAST:event_t3ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        // TODO add your handling code here:
        if (str.length() > 0 && !(str.endsWith("+"))) {
            if (str.endsWith("-")) {
                str = str.substring(0, str.length() - 1);
                op1ActionPerformed(evt);
                return;
            }
            if (str.endsWith("*")) {
                str = str.substring(0, str.length() - 1);
                op1ActionPerformed(evt);
                return;
            }
            if (str.endsWith("/")) {
                str = str.substring(0, str.length() - 1);
                op1ActionPerformed(evt);
                return;
            }
            op = 1;
            pflag = nflag;
            nflag = (nflag + 1) % 2;
            System.out.println(pflag + " " + nflag);
            str1 = ans;
            str2 = "";
            str += "+";
            t1.setText(str);
        } else {
            System.out.println("Invalid");
        }
    }//GEN-LAST:event_op1ActionPerformed

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
        // TODO add your handling code here:
        if (str.length() > 0 && !(str.endsWith("-"))) {
            if (str.endsWith("+")) {
                str = str.substring(0, str.length() - 1);
                op2ActionPerformed(evt);
                return;
            }
            if (str.endsWith("*")) {
                str = str.substring(0, str.length() - 1);
                op2ActionPerformed(evt);
                return;
            }
            if (str.endsWith("/")) {
                str = str.substring(0, str.length() - 1);
                op2ActionPerformed(evt);
                return;
            }
            op = 2;
            pflag = nflag;
            nflag = (nflag + 1) % 2;
            System.out.println(pflag + " " + nflag);
            str1 = ans;
            str2 = "";
            str += "-";
            t1.setText(str);
        } else {
            System.out.println("Invalid");
        }
    }//GEN-LAST:event_op2ActionPerformed

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3ActionPerformed
        // TODO add your handling code here:
        if (str.length() > 0 && !(str.endsWith("*"))) {
            if (str.endsWith("-")) {
                str = str.substring(0, str.length() - 1);
                op3ActionPerformed(evt);
                return;
            }
            if (str.endsWith("+")) {
                str = str.substring(0, str.length() - 1);
                op3ActionPerformed(evt);
                return;
            }
            if (str.endsWith("/")) {
                str = str.substring(0, str.length() - 1);
                op3ActionPerformed(evt);
                return;
            }
            op = 3;
            pflag = nflag;
            nflag = (nflag + 1) % 2;
            System.out.println(pflag + " " + nflag);
            str1 = ans;
            str2 = "";
            str += "*";
            t1.setText(str);
        } else {
            System.out.println("Invalid");
        }
    }//GEN-LAST:event_op3ActionPerformed

    private void op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4ActionPerformed
        // TODO add your handling code here:
        if (str.length() > 0 && !(str.endsWith("/"))) {
            if (str.endsWith("-")) {
                str = str.substring(0, str.length() - 1);
                op4ActionPerformed(evt);
                return;
            }
            if (str.endsWith("*")) {
                str = str.substring(0, str.length() - 1);
                op4ActionPerformed(evt);
                return;
            }
            if (str.endsWith("+")) {
                str = str.substring(0, str.length() - 1);
                op4ActionPerformed(evt);
                return;
            }
            op = 4;
            pflag = nflag;
            nflag = (nflag + 1) % 2;
            System.out.println(pflag + " " + nflag);
            str1 = ans;
            str2 = "";
            str += "/";
            t1.setText(str);
        } else {
            System.out.println("Invalid");
        }
    }//GEN-LAST:event_op4ActionPerformed

    private void op5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op5ActionPerformed
        // TODO add your handling code here:
        String temp = str;
        str = ans;
        str1 = "";
        str2 = "";
        ans = "";
        pflag = 0;
        nflag = 0;
        op = 0;
        DecimalFormat df = new DecimalFormat("#.######");
        if (str.length() > 0) {

            t3.addItem(temp + "=" + df.format(Double.parseDouble(str)));
            t1.setText(df.format(Double.parseDouble(str)));
        }
        str = "";
    }//GEN-LAST:event_op5ActionPerformed

    private void op6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op6ActionPerformed
        // TODO add your handling code here:
        if (str.endsWith("+") || str.endsWith("-") || str.endsWith("*") || str.endsWith("/")) {
            str = str.substring(0, str.length() - 1);
            if (!(str.contains("+") || str.contains("-") || str.contains("*") || str.contains("/"))) {
                str1 = str;
                str2 = "0";
                nflag = pflag = 0;
                op = 0;
                t1.setText(str);
                System.out.println(str1 + " " + str2);
                System.out.println(pflag + " " + nflag);
            } else {
                int maxi = Math.max(Math.max(str.lastIndexOf("+"), str.lastIndexOf("-")), Math.max(str.lastIndexOf("*"), str.lastIndexOf("/")));
                str2 = str.substring(maxi + 1);
                switch (str.charAt(maxi)) {
                    case '+' ->
                        op = 1;
                    case '-' ->
                        op = 2;
                    case '*' ->
                        op = 3;
                    case '/' ->
                        op = 4;
                    default -> {
                        op = 0;
                    }
                }

                switch (op) {
                    case 1 ->
                        str1 = String.valueOf(Double.parseDouble(ans) - Double.parseDouble(str2));
                    case 2 ->
                        str1 = String.valueOf(Double.parseDouble(ans) + Double.parseDouble(str2));
                    case 3 ->
                        str1 = String.valueOf(Double.parseDouble(ans) / Double.parseDouble(str2));
                    case 4 ->
                        str1 = String.valueOf(Double.parseDouble(ans) * Double.parseDouble(str2));
                    default -> {
                        ans = str;
                    }
                }
                pflag = nflag;
                nflag = (nflag + 1) % 2;
                t1.setText(str);
                System.out.println(str1 + " " + str2);
                System.out.println(pflag + " " + nflag);
            }
        } else {
            if (str.length() > 0) {
                str = str.substring(0, str.length() - 1);
            }
            if (nflag == pflag && str1.length() > 0) {
                str1 = str1.substring(0, str1.length() - 1);
            } else if (str2.length() > 0) {
                str2 = str2.substring(0, str2.length() - 1);
            }
            if (str1.equals("")) {
                str1 = "0";
            }
            if (str2.equals("")) {
                if (op == 3 || op == 4) {
                    str2 = "1";
                } else {
                    str2 = "0";
                }
            }
            switch (op) {
                case 1 ->
                    ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
                case 2 ->
                    ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
                case 3 ->
                    ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
                case 4 ->
                    ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
                default -> {
                    ans = str1;
                }
            }
            t1.setText(str);
            DecimalFormat df = new DecimalFormat("#.######");
            t2.setText(df.format(Double.parseDouble(ans)));
            System.out.println(str1 + " " + str2);
            System.out.println(pflag + " " + nflag);
        }
    }//GEN-LAST:event_op6ActionPerformed

    private void op7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op7ActionPerformed

    private void op8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op8ActionPerformed

    private void op9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op9ActionPerformed
        // TODO add your handling code here:
        str="";
        str1 = "0";
        str2 = "";
        ans = "";
        pflag = 0;
        nflag = 0;
        op = 0;
        t1.setText("0");
        t2.setText("0");
    }//GEN-LAST:event_op9ActionPerformed

    private void op10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op10ActionPerformed
        // TODO add your handling code here:
         if(str.length()<=0){
            System.out.println("Invalid");
        }else{
            
        if (nflag == pflag) {
            if (!str1.contains(".")) {
                str += ".";
                str1 += ".";
            } else {
                System.out.println("Invalid");
            }
        } else {
            if (!str2.contains(".")) {
                str += ".";
                str2 += ".";
            } else {
                System.out.println("Invalid");
            }
        }
        if (str2.equals("")) {
            str2 = "0";
        }
        switch (op) {
            case 1 ->
                ans = String.valueOf(Double.parseDouble(str1) + Double.parseDouble(str2));
            case 2 ->
                ans = String.valueOf(Double.parseDouble(str1) - Double.parseDouble(str2));
            case 3 ->
                ans = String.valueOf(Double.parseDouble(str1) * Double.parseDouble(str2));
            case 4 ->
                ans = String.valueOf(Double.parseDouble(str1) / Double.parseDouble(str2));
            default -> {
                ans = str1;
            }
        }
        t1.setText(str);
        DecimalFormat df = new DecimalFormat("#.######");
        t2.setText(df.format(Double.parseDouble(ans)));
        }
    }//GEN-LAST:event_op10ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton num1;
    private javax.swing.JButton num10;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton op1;
    private javax.swing.JButton op10;
    private javax.swing.JButton op2;
    private javax.swing.JButton op3;
    private javax.swing.JButton op4;
    private javax.swing.JButton op5;
    private javax.swing.JButton op6;
    private javax.swing.JButton op7;
    private javax.swing.JButton op8;
    private javax.swing.JButton op9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JComboBox<String> t3;
    // End of variables declaration//GEN-END:variables
}
